### ISSUE TITLE
problem with Store Hours

### ISSUE THREAD

**Issue by byTwinn** [kffein/Craft-export-Csv#3]
Hi  from Belgium,

I use a plugin called "Store Hours" (from creator of craft) that create a field type to Craft for collecting the opening and closing hours but when I try to export a entry with this field, the operation end by a fail.

here is the content of this field in DB : 

[{"open":null,"close":null},{"open":"2018-12-07 07:36:00","close":"2018-12-07 17:00:00"},{"open":null,"close":null},{"open":null,"close":null},{"open":null,"close":null},{"open":null,"close":null},{"open":null,"close":null}]

Do you have an idea? thanks

**Comment by jlachancekffein** [comment]
Hi,

Is it possible for you to send me a dump of your DB with a CP access ?

This will help me to debug your problem.

You can send me the file at joel@kffein.com

Thank you.

**Comment by jlachancekffein** [comment]
Thanks for submitting all the needed informations.

I found the problem and it should working correctly. 

The problem was due to unhandle array/object value. Now, array/object are converted to string with json_encode(). 

To fix on your side, please update with the version v1.0.6. > composer update.

I will wait for confirmation on your side before closing this issue.

Have a nice day.

**Comment by byTwinn** [comment]
wonderfull ! I'll test tomorrow at office and keep you informed.

Thanks again
